version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: task-management:1.0
    container_name: task-management-app
    ports:
      - "8082:8082"
    volumes:
      - "./cmd/api/config.yaml:/app/cmd/api/config.yaml"
      - "./cmd/api/appLogs.txt:/app/appLogs.txt"
    restart: unless-stopped
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    container_name: task-management-db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh"
      - "./Task-manager.sql:/app/Task-manager.sql"

  redis:
    image: redis:alpine
    container_name: task-management-cache
    ports:
      - "6379:6379"
