version: '3.8'

services:
  app:
    image: task-management:1.0
    ports:
      - "8082:8082"
    volumes:
      - "./cmd/api/config.yaml:/app/cmd/api/config.yaml"
    restart: on-failure
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
