server:
  http_port: 8080
  host: "localhost"
  token_exp_minutes: 1440
  refresh_token_exp_minute: 2880 
  token_secret: "P@$$%Secret6677"
  max_rate_limit: 15
  rate_limit_expiration: 30
db:
  user: "postgres"
  pass: "postgres"
  host : "localhost"
  port: 5432
  db_name: "task-management"
redis:
  address: "localhost:6379"
  password: ""
  db: 0
email:
  smtp_host: "mail.email.com"
  smtp_port: 587
  smtp_username: "noreply@email.com"
  smtp_password: "secret"
  smtp_from_address: "noreply@email.com"
  smtp_encryption: "tls"
  smtp_from_name: "noreply@email.com"