basePath: /api/v1
definitions:
  domain.Board:
    properties:
      createdBy:
        type: integer
      id:
        type: integer
      isPrivate:
        type: boolean
      name:
        type: string
    type: object
  handlers.CreateBoardRequest:
    properties:
      is_private:
        example: false
        type: boolean
      name:
        example: new board
        maxLength: 50
        minLength: 3
        type: string
    required:
    - name
    type: object
  handlers.LoginInput:
    properties:
      email:
        example: test1@test.com
        type: string
      password:
        example: 1234Test@
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  handlers.SignUpInput:
    properties:
      email:
        example: test@example.com
        type: string
      name:
        example: test
        maxLength: 20
        minLength: 3
        type: string
      password:
        example: 1234Test@
        minLength: 8
        type: string
    required:
    - email
    - name
    - password
    type: object
  handlers.UpdateBoardRequest:
    properties:
      is_private:
        example: false
        type: boolean
      name:
        example: new board
        maxLength: 50
        minLength: 3
        type: string
    required:
    - name
    type: object
host: localhost:8082
info:
  contact:
    name: GoBootcamp-Group1
    url: https://github.com/GoBootCamp-Group1
  description: This is a task management application.
  title: Task Manager
  version: "1.0"
paths:
  /boards:
    post:
      consumes:
      - application/json
      description: creates a board
      parameters:
      - description: Create Board
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateBoardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Create Board
      tags:
      - Create Board
  /boards/{id}:
    delete:
      description: deleted a board
      parameters:
      - description: Board ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Delete Board
      tags:
      - Delete Board
    get:
      description: gets a board
      parameters:
      - description: Board ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Board'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Get Board
      tags:
      - Get Board
    put:
      consumes:
      - application/json
      description: updates a board
      parameters:
      - description: Board ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Board
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.UpdateBoardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Update Board
      tags:
      - Update Board
  /login:
    post:
      consumes:
      - application/json
      description: login user with email and password
      parameters:
      - description: User Login
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: User login
      tags:
      - Login
  /signup:
    post:
      consumes:
      - application/json
      description: Register a user with email, name and password
      parameters:
      - description: User Registration
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.SignUpInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: User registration
      tags:
      - SignUp
security:
- ApiKeyAuth: []
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
