basePath: /api/v1
definitions:
  domains.Board:
    properties:
      createdBy:
        type: integer
      id:
        type: integer
      isPrivate:
        type: boolean
      name:
        type: string
    type: object
  domains.Column:
    properties:
      board_id:
        type: integer
      created_by:
        type: integer
      id:
        type: integer
      is_final:
        type: boolean
      name:
        type: string
      order_position:
        type: integer
    type: object
  handlers.ChangeUserRoleRequest:
    properties:
      role_name:
        type: string
    type: object
  handlers.CreateBoardRequest:
    properties:
      is_private:
        example: false
        type: boolean
      name:
        example: new board
        maxLength: 50
        minLength: 3
        type: string
    required:
    - name
    type: object
  handlers.CreateColumnRequest:
    properties:
      is_final:
        example: false
        type: boolean
      name:
        example: new column
        maxLength: 20
        minLength: 3
        type: string
    required:
    - name
    type: object
  handlers.InviteUserRequest:
    properties:
      role_name:
        type: string
      user_id:
        type: integer
    type: object
  handlers.LoginInput:
    properties:
      email:
        example: test1@test.com
        type: string
      password:
        example: 1234Test@
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  handlers.SignUpInput:
    properties:
      email:
        example: test@example.com
        type: string
      name:
        example: test
        maxLength: 20
        minLength: 3
        type: string
      password:
        example: 1234Test@
        minLength: 8
        type: string
    required:
    - email
    - name
    - password
    type: object
  handlers.TaskRequest:
    type: object
  handlers.UpdateBoardRequest:
    properties:
      is_private:
        example: false
        type: boolean
      name:
        example: new board
        maxLength: 50
        minLength: 3
        type: string
    required:
    - name
    type: object
host: 0.0.0.0:8082
info:
  contact:
    name: GoBootcamp-Group1
    url: https://github.com/GoBootCamp-Group1
  description: This is a task management application.
  title: Task Manager
  version: "1.0"
paths:
  /boards:
    post:
      consumes:
      - application/json
      description: creates a board
      parameters:
      - description: Create Board
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateBoardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Create Board
      tags:
      - Board
  /boards/{board_id}/users/{user_id}:
    delete:
      consumes:
      - application/json
      description: removes a user from board
      parameters:
      - description: Board ID
        in: path
        name: board_id
        required: true
        type: string
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Remove User from Board
      tags:
      - Board
    put:
      consumes:
      - application/json
      description: changes user role in board
      parameters:
      - description: Board ID
        in: path
        name: board_id
        required: true
        type: string
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: Create Board
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.ChangeUserRoleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Change User Role in Board
      tags:
      - Board
  /boards/{boardID}/tasks/{id}:
    delete:
      description: deleted a task
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Delete Task
      tags:
      - Task
  /boards/{boardID}/tasks/{taskID}:
    put:
      consumes:
      - application/json
      description: updates a task
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Task
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.TaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Update Task
      tags:
      - Task
  /boards/{id}:
    delete:
      description: deleted a board
      parameters:
      - description: Board ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Delete Board
      tags:
      - Board
    get:
      description: gets a board
      parameters:
      - description: Board ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domains.Board'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Get Board
      tags:
      - Board
    put:
      consumes:
      - application/json
      description: updates a board
      parameters:
      - description: Board ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Board
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.UpdateBoardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Update Board
      tags:
      - Board
  /boards/{id}/add-user:
    post:
      consumes:
      - application/json
      description: invites a user to board
      parameters:
      - description: Board ID
        in: path
        name: id
        required: true
        type: string
      - description: Create Board
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.InviteUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Invite User to Board
      tags:
      - Board
  /columns:
    get:
      description: gets all columns of a bard
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domains.Column'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Get Columns
      tags:
      - Column
  /columns/{boardId}:
    post:
      consumes:
      - application/json
      description: create a column
      parameters:
      - description: Create Column
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateColumnRequest'
      - description: Board ID
        in: path
        name: boardId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Create Column
      tags:
      - Column
  /columns/{id}:
    delete:
      consumes:
      - application/json
      description: delete a column
      parameters:
      - description: Column ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Delete Column
      tags:
      - Column
    get:
      description: gets a column
      parameters:
      - description: Column ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domains.Column'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Get Column
      tags:
      - Column
    put:
      consumes:
      - application/json
      description: update a column
      parameters:
      - description: Column ID
        in: path
        name: id
        required: true
        type: string
      - description: New Column name
        in: body
        name: name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domains.Column'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Update Column
      tags:
      - Column
  /columns/{id}/final:
    put:
      consumes:
      - application/json
      description: make a column as a final column
      parameters:
      - description: Column ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domains.Column'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Final Column
      tags:
      - Column
  /columns/{id}/move:
    put:
      consumes:
      - application/json
      description: move a column
      parameters:
      - description: Column ID
        in: path
        name: id
        required: true
        type: string
      - description: new position of column [id]
        in: body
        name: order_position
        required: true
        schema:
          type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domains.Column'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Move Column
      tags:
      - Column
  /login:
    post:
      consumes:
      - application/json
      description: login user with email and password
      parameters:
      - description: User Login
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: User login
      tags:
      - Authentication
  /signup:
    post:
      consumes:
      - application/json
      description: Register a user with email, name and password
      parameters:
      - description: User Registration
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.SignUpInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: User registration
      tags:
      - Authentication
  /tasks:
    post:
      consumes:
      - application/json
      description: creates a task
      parameters:
      - description: Create Task
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.TaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Create Task
      tags:
      - Task
security:
- ApiKeyAuth: []
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
